### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by abelsiqueira** [ufpr-opt/perprof-py#129]
I suggest we make a new release before the JORS article.
Let's call it v1.1? What shall be included?

**Comment by lrsantos11** [comment]
I agree that we could call this release v1.1 for the JORS paper. We need @r-gaia-cs opinion here on what shall be included.

**Comment by r-gaia-cs** [comment]
I will not have time to look on this issue until next week.

**Comment by r-gaia-cs** [comment]
The issues and pull request marked for [1.1](https://github.com/ufpr-opt/perprof-py/milestones/Version%201.2).
