### ISSUE TITLE
add option to display a title

### ISSUE THREAD

**Issue by mattmilten** [ufpr-opt/perprof-py#161]
It would be nice to be able to supply an additional option ,e.g. `--title=testset`, that would then be displayed as title of the figure.

**Comment by abelsiqueira** [comment]
Hi @mattmilten, thanks for the interest. I'll take a look into it. Probably easy to do.

**Comment by mattmilten** [comment]
Thanks! The title option does not work, though, when put into a perprof settings file loaded with the @ option.
