### ISSUE TITLE
Title with @ option

### ISSUE THREAD

**Issue by rgaiacs** [ufpr-opt/perprof-py#164]
From @mattmilten 

> Thanks! The title option does not work, though, when put into a perprof settings file loaded with the @ option.

**Comment by rgaiacs** [comment]
Maybe a duplicate of https://github.com/ufpr-opt/perprof-py/issues/166?

**Comment by rgaiacs** [comment]
@mattmilten Could you check if https://github.com/ufpr-opt/perprof-py/issues/166#issuecomment-164208198 solve your problem?

**Comment by mattmilten** [comment]
Yes, it works perfectly if the title is on a new line after `--title`. Thanks!

**Comment by rgaiacs** [comment]
@mattmilten Thanks for the feedback. We are going to update the documentation soon.
