### ISSUE TITLE
Many files

### ISSUE THREAD

**Issue by abelsiqueira** [ufpr-opt/perprof-py#169]
Perprof doesn't handle well many files. On TikZ, colors will repeat after 8 curves.

**Comment by rgaiacs** [comment]
> Perprof doesn't handle well many files.

How many files do you expect that we handle?

What about warning the user about many input files?

**Comment by abelsiqueira** [comment]
Didn't decide yet. Maybe 30?

**Comment by rgaiacs** [comment]
> Maybe 30?

Do you have some "logic" explanation for why 30 and not any other number?

**Comment by abelsiqueira** [comment]
[BBcomp](http://bbcomp.ini.rub.de/results/BBComp2015GECCO/summary.html) had 29 submissions.

**Comment by abelsiqueira** [comment]
This can be very complicated due to the multiplicity of things, and visibility of variables. So maybe change this to an error: maximum number of different line styles reached. And then add a enhancement issue to increase the maximum number of diff line styles.

**Comment by abelsiqueira** [comment]
Fixed
